# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:blueprinttest/animations/animation_model_new/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.animation_model_new.frame 1