# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.blueprinttest.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blueprinttest', 'function_path': 'animated_java:blueprinttest/animations/animation_model_new/next_frame'}
execute if score @s aj.animation_model_new.frame matches 81.. run scoreboard players set @s aj.animation_model_new.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.animation_model_new.frame
execute at @s run function animated_java:blueprinttest/animations/animation_model_new/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.animation_model_new.frame 1