# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.core] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_core set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.blueprinttest.bone.flipper8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flipper8 set from storage aj:uuid main.out