# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.blueprinttest.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blueprinttest', 'function_path': 'animated_java:blueprinttest/variants/default/apply'}
execute on passengers if entity @s[tag=aj.blueprinttest.bone.core] run function animated_java:blueprinttest/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper] run function animated_java:blueprinttest/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper2] run function animated_java:blueprinttest/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper3] run function animated_java:blueprinttest/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper4] run function animated_java:blueprinttest/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper5] run function animated_java:blueprinttest/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper6] run function animated_java:blueprinttest/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper7] run function animated_java:blueprinttest/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.blueprinttest.bone.flipper8] run function animated_java:blueprinttest/variants/default/zzz/8